# TCL File Generated by Component Editor 18.1
# Mon Feb 19 10:16:24 GMT 2024
# DO NOT MODIFY


# 
# power3 "power3" v1.0
#  2024.02.19.10:16:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module power3
# 
set_module_property DESCRIPTION ""
set_module_property NAME power3
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME power3
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL power3
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file power3.sv SYSTEM_VERILOG PATH ../rtl/power3.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point power3
# 
add_interface power3 nios_custom_instruction end
set_interface_property power3 clockCycle 4
set_interface_property power3 operands 1
set_interface_property power3 ENABLED true
set_interface_property power3 EXPORT_OF ""
set_interface_property power3 PORT_NAME_MAP ""
set_interface_property power3 CMSIS_SVD_VARIABLES ""
set_interface_property power3 SVD_ADDRESS_GROUP ""

add_interface_port power3 i_clk clk Input 1
add_interface_port power3 i_srst reset Input 1
add_interface_port power3 i_x dataa Input 32
add_interface_port power3 o_xPower result Output 32
add_interface_port power3 i_clkEn clk_en Input 1

